[package]
name = "rust_single_server_queue"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3"
plotters = "0.3.7"
eframe = "0.32"
egui_plot = "0.33"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
