[package]
name = "rust_single_server_queue"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "2.0"
plotters = "0.3"
eframe = "0.29"
egui = "0.29"
egui_plot = "0.29"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
